version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3305:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - crud-network

  demo-spring-mysql-restapi-demo:
    image: lokytech/demo-spring-mysql-restapi-demo:0.0.1-SNAPSHOT
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/SpringMySqlRestApiDemo_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - crud-network

volumes:
  db_data:


networks:
  crud-network:
